### ISSUE TITLE
batch_mode=True, find_tad method  exit python interpreter and show 'Segmentation fault: 11' 

### ISSUE THREAD

**Issue by faustson** [3DGenomes/TADbit#187] opened 2017-08-01 22:05 UTC
I am a new guy using Hi-C analysis, I just follow 'the Identification and Analysis of TADs and Compartments' part, when running the code my_chrom.find_tad(['k562', 'gm06690'], batch_mode=True, n_cpus=4) under python interpreter, it will just run a few cycles and then jump out python , show 'Segmentation fault: 11', like following:

>>>
running pre-heuristic
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
Segmentation fault: 11

Now I am running TADbit under OSX EI Capitan 10.11.6, python 2.7.13
Thanks!
Kun

**Comment by fransua** [comment] 2017-08-09 10:45
Hi Kun,
I am not able to reproduce your error, and this is what I executed in my machine:
```
from pytadbit import Chromosome

# initiate a chromosome object that will store all Hi-C data and analysis
my_chrom = Chromosome(name='chr19', centromere_search=True,
                      species='Homo sapiens', assembly='NCBI36')

# load Hi-C data
my_chrom.add_experiment('k562', cell_type='wild type', exp_type='Hi-C', identifier='k562',
                        project='TADbit tutorial',
                        hic_data="sample_data/HIC_k562_chr19_chr19_100000_obs.txt", resolution=100000)

my_chrom.add_experiment('gm06690',  cell_type='cancer', exp_type='Hi-C', identifier='gm06690',
                        project='TADbit tutorial',
                        hic_data="sample_data/HIC_gm06690_chr19_chr19_100000_obs.txt", resolution=100000)

my_chrom.find_tad(['k562', 'gm06690'], batch_mode=True, n_cpus=4)

my_chrom.tad_density_plot('batch_gm06690_k562')
```
![image](https://user-images.githubusercontent.com/106498/29117958-7ccd496a-7d00-11e7-8334-c907dcce0e60.png)

Can you let me know if you used the same input files HIC_gm06690_chr19_chr19_100000_obs.txt and HIC_k562_chr19_chr19_100000_obs.txt provided in the sample_data as in the tutorial.
Also can you paste here the result of this command:

`python -c 'import pytadbit; print pytadbit.get_dependencies_version()'`

thanks

**Comment by faustson** [comment] 2017-08-09 17:32
Yes, I think so, I just download directly from the folder TADbit/scripts/sample_data/.  I modified nothing to these two input files(HIC_gm06690_chr19_chr19_100000_obs.txt, HIC_k562_chr19_chr19_100000_obs.txt ). Actually if I set the 'batch_mode = False', it seems OK but runs very slowly. This is what I get with 'batch_mode = False':
>>>my_chrom.find_tad(['k562', 'gm06690'], batch_mode=False, n_cpus=4)
running pre-heuristic
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
running pre-heuristic
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)
starting new cycle
computing likelihood (100% done)

 >>> print my_chrom.experiments
[Experiment k562 (resolution: 100 kb, TADs: 37, Hi-C rows: 639, normalized: None), Experiment gm06690 (resolution: 100 kb, TADs: 35, Hi-C rows: 639, normalized: None)]

There is no experiment called 'batch_gm06690_k562'

This is what I got after I ran python -c 'import pytadbit; print pytadbit.get_dependencies_version()'
         TADbit : v0.2.51
     Machine : 
            IMP : 2.7.0 (random seed indexed at 1 = 1791095845)
            MCL : 14-137
     gem-mapper : Not found
       gemtools : Not found
     matplotlib : 1.2.1
          numpy : 1.9.0
          scipy : 0.13.2

**Comment by fransua** [comment] 2018-01-20 11:13
Issue should be fixed now, since: https://github.com/3DGenomes/TADbit/commit/393ed7a806d9b9e2795dc45c1ddcb1302ce381a5

**Closed by fransua** 2018-01-20 11:13 UTC

**Comment by faustson** [comment] 2018-01-20 21:14
Great! Thanks!

Best,
Kun
